"""Executor 4: Mitigation Decision Agent.

Decides a primary mitigation action per risk alert (switch transport mode,
expedite, or just request a carrier ETA update) plus a customer-notification
companion action when sales orders are affected, then routes every action to
auto-execute or human-escalation per the confidence / cost thresholds.

The `reasoning` field on each action is generated by an LLM when
AZURE_AI_PROJECT_ENDPOINT is configured (see `_llm_reasoning`); otherwise it
falls back to a deterministic explanation built from the same facts. The LLM
call is best-effort — any failure (missing credentials, network, auth) is
caught and silently falls back, so the pipeline behaves identically with or
without Azure OpenAI configured.
"""

import logging

from agent_framework import Executor, WorkflowContext, handler

from src.config import settings
from src.models.mitigation import ActionType
from src.models.shipment import Shipment, TransportMode
from src.state import ImpactAssessment, ImpactReport, MitigationAction, MitigationPlan, RiskAlert

logger = logging.getLogger("supply_chain_agent.mitigation")

# Rough action-cost / confidence proxies — no real carrier-quote or historical
# success-rate data exists in the mock dataset, so these are heuristic constants
# rather than config-driven thresholds (which govern *routing*, not estimation).
_SWITCH_MODE_COST = 45_000.0
_SWITCH_MODE_CONFIDENCE = 0.65
_EXPEDITE_FASTEST_MODE_COST = 20_000.0
_EXPEDITE_FASTEST_MODE_CONFIDENCE = 0.70
_EXPEDITE_STOCKOUT_COST = 12_000.0
_NOTIFY_CARRIER_CONFIDENCE = 0.90
_NOTIFY_CUSTOMER_CONFIDENCE = 0.95


def _primary_action(
    shipment: Shipment | None, assessment: ImpactAssessment, alert: RiskAlert
) -> tuple[ActionType, float, float, float, str]:
    """Returns (action_type, confidence, estimated_cost, delay_reduction_days, description)."""
    plant = assessment.affected_plants[0] if assessment.affected_plants else "the destination plant"
    mode = shipment.mode if shipment else None

    if assessment.production_stoppage_risk:
        if mode is not None and mode != TransportMode.AIR:
            return (
                ActionType.SWITCH_TRANSPORT_MODE,
                _SWITCH_MODE_CONFIDENCE,
                _SWITCH_MODE_COST,
                round(alert.estimated_delay_days * 0.8, 1),
                f"Switch {alert.shipment_id} from {mode.value} to air freight to prevent a production "
                f"stoppage at {plant}",
            )
        return (
            ActionType.EXPEDITE_SHIPMENT,
            _EXPEDITE_FASTEST_MODE_CONFIDENCE,
            _EXPEDITE_FASTEST_MODE_COST,
            round(alert.estimated_delay_days * 0.5, 1),
            f"Expedite {alert.shipment_id} (already on the fastest available mode) to prevent a "
            f"production stoppage at {plant}",
        )

    if assessment.stockout_risk:
        confidence = min(0.95, 0.6 + 0.1 * len(alert.sources))
        return (
            ActionType.EXPEDITE_SHIPMENT,
            confidence,
            _EXPEDITE_STOCKOUT_COST,
            round(alert.estimated_delay_days * 0.5, 1),
            f"Expedite {alert.shipment_id} — inventory at {plant} is below safety stock",
        )

    return (
        ActionType.NOTIFY_CARRIER,
        _NOTIFY_CARRIER_CONFIDENCE,
        0.0,
        0.0,
        f"Request an updated ETA from the carrier for {alert.shipment_id}",
    )


def _notify_customer_action(alert: RiskAlert, assessment: ImpactAssessment) -> MitigationAction:
    so_ids = ", ".join(assessment.affected_sales_orders)
    return MitigationAction(
        action_id=f"ACT-{alert.alert_id}-NOTIFY",
        alert_id=alert.alert_id,
        shipment_id=alert.shipment_id,
        action_type=ActionType.NOTIFY_CUSTOMER.value,
        description=f"Notify affected sales orders ({so_ids}) of a possible delay on {alert.shipment_id}",
        confidence=_NOTIFY_CUSTOMER_CONFIDENCE,
        estimated_cost=0.0,
        estimated_delay_reduction_days=0.0,
        reasoning=(
            f"{alert.shipment_id} is at risk ({', '.join(alert.sources)}, score {alert.risk_score}) and "
            f"affects sales orders {so_ids}; a proactive heads-up carries no cost or downside."
        ),
    )


def _fallback_reasoning(
    alert: RiskAlert,
    assessment: ImpactAssessment,
    action_type: ActionType,
    confidence: float,
    cost: float,
    delay_reduction: float,
) -> str:
    return (
        f"{alert.shipment_id} triggered {', '.join(alert.sources)} (risk score {alert.risk_score}). "
        f"{assessment.summary} Recommended: {action_type.value} "
        f"(confidence {confidence:.2f}, est. cost ${cost:,.0f}, est. delay reduction {delay_reduction}d)."
    )


def _llm_prompt(alert: RiskAlert, assessment: ImpactAssessment, action_type: ActionType, description: str) -> str:
    return (
        "You are a supply chain risk analyst. Given the facts below, write a concise "
        "2-3 sentence justification for the recommended mitigation action.\n\n"
        f"Shipment: {alert.shipment_id}\n"
        f"Risk signals: {', '.join(alert.sources)} (risk score {alert.risk_score})\n"
        f"Impact: {assessment.summary}\n"
        f"Recommended action: {action_type.value} — {description}\n"
    )


async def _llm_reasoning(prompt: str) -> str | None:
    """Best-effort LLM call for the reasoning narrative. Returns None on any failure."""
    if not settings.azure_ai_project_endpoint:
        return None
    try:
        from agent_framework import Message
        from agent_framework_openai import OpenAIChatClient
        from azure.identity.aio import DefaultAzureCredential, get_bearer_token_provider
        from openai import AsyncAzureOpenAI

        async with DefaultAzureCredential() as credential:
            token_provider = get_bearer_token_provider(credential, "https://cognitiveservices.azure.com/.default")
            azure_client = AsyncAzureOpenAI(
                azure_endpoint=settings.azure_ai_project_endpoint,
                azure_deployment=settings.model_deployment_name,
                api_version="2024-10-21",
                azure_ad_token_provider=token_provider,
            )
            chat_client = OpenAIChatClient(async_client=azure_client)
            response = await chat_client.get_response([Message("user", [prompt])])
            return response.text.strip() or None
    except Exception:
        logger.warning("LLM reasoning unavailable, falling back to rule-based explanation", exc_info=True)
        return None


def _route_actions(actions: list[MitigationAction]) -> tuple[list[MitigationAction], list[MitigationAction]]:
    auto_actions: list[MitigationAction] = []
    escalation_actions: list[MitigationAction] = []
    for action in actions:
        if action.estimated_cost > settings.cost_escalation_threshold:
            escalation_actions.append(action)
        elif action.confidence >= settings.confidence_threshold:
            auto_actions.append(action)
        else:
            escalation_actions.append(action)
    return auto_actions, escalation_actions


class MitigationExecutor(Executor):
    """Proposes mitigation actions per risk alert and routes auto vs. escalation."""

    @handler
    async def process(self, message: ImpactReport, ctx: WorkflowContext[MitigationPlan]) -> None:
        logger.info(f"Mitigation: proposing actions for {len(message.assessments)} impact(s)...")

        alerts_by_id = {a.alert_id: a for a in message.alerts}
        shipments_by_id = {
            s.shipment_id: s for s in (message.ingested_data.shipments if message.ingested_data else [])
        }

        actions: list[MitigationAction] = []
        for assessment in message.assessments:
            alert = alerts_by_id.get(assessment.alert_id)
            if alert is None:
                continue
            shipment = shipments_by_id.get(assessment.shipment_id)

            action_type, confidence, cost, delay_reduction, description = _primary_action(
                shipment, assessment, alert
            )
            fallback = _fallback_reasoning(alert, assessment, action_type, confidence, cost, delay_reduction)
            reasoning = await _llm_reasoning(_llm_prompt(alert, assessment, action_type, description)) or fallback

            actions.append(
                MitigationAction(
                    action_id=f"ACT-{alert.alert_id}-PRIMARY",
                    alert_id=alert.alert_id,
                    shipment_id=alert.shipment_id,
                    action_type=action_type.value,
                    description=description,
                    confidence=confidence,
                    estimated_cost=cost,
                    estimated_delay_reduction_days=delay_reduction,
                    reasoning=reasoning,
                )
            )

            if assessment.affected_sales_orders:
                actions.append(_notify_customer_action(alert, assessment))

        auto_actions, escalation_actions = _route_actions(actions)

        logger.info(
            f"Mitigation complete: {len(actions)} action(s) — "
            f"{len(auto_actions)} auto, {len(escalation_actions)} escalated"
        )
        for a in actions:
            logger.info(
                f"  {a.action_id} | {a.action_type:<22} | confidence={a.confidence:.2f} | "
                f"cost=${a.estimated_cost:,.0f}"
            )

        await ctx.send_message(
            MitigationPlan(actions=actions, auto_actions=auto_actions, escalation_actions=escalation_actions)
        )
